'use strict';

const fc = require('fast-check');

/**
 * Property 3: Recording requests use JWT authentication
 *
 * For any call to startRecording, the outbound HTTP request SHALL include
 * an Authorization header with value `Bearer <token>` where the token is
 * a non-empty string generated by generateJwt().
 *
 * **Validates: Requirements 2.3**
 */
describe('Feature: api-driven-recording, Property 3: Recording requests use JWT authentication', () => {
  let startRecording;
  let mockRequest;

  beforeEach(() => {
    jest.resetModules();

    // Generate a dummy RSA private key for JWT signing
    const crypto = require('crypto');
    const { privateKey } = crypto.generateKeyPairSync('rsa', {
      modulusLength: 2048,
      publicKeyEncoding: { type: 'pkcs1', format: 'pem' },
      privateKeyEncoding: { type: 'pkcs1', format: 'pem' },
    });
    const privateKey64 = Buffer.from(privateKey).toString('base64');

    // Mock config
    jest.mock('../config', () => ({
      VONAGE_APPLICATION_ID: 'test-app-id',
      VONAGE_PRIVATE_KEY64: 'dummy',
    }));
    // Override the mocked value with the real key
    require('../config').VONAGE_PRIVATE_KEY64 = privateKey64;

    // Mock https module using manual approach to avoid out-of-scope variable issues
    mockRequest = jest.fn();
    jest.mock('https', () => ({
      request: (...args) => mockRequest(...args),
    }));

    // Configure mockRequest to simulate a successful response
    mockRequest.mockImplementation((options, callback) => {
      const { EventEmitter } = require('events');
      const res = new EventEmitter();
      res.statusCode = 200;
      process.nextTick(() => {
        callback(res);
        res.emit('data', JSON.stringify({ id: 'rec-123', status: 'started' }));
        res.emit('end');
      });
      const req = new EventEmitter();
      req.write = jest.fn();
      req.end = jest.fn();
      return req;
    });

    startRecording = require('./vonage').startRecording;
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('Authorization header has Bearer <non-empty-token> format for any conversation UUID', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 1, maxLength: 100 }).filter(s => s.trim().length > 0),
        async (conversationUuid) => {
          mockRequest.mockClear();

          await startRecording(conversationUuid, 'http://example.com/recordings');

          // Verify https.request was called
          expect(mockRequest).toHaveBeenCalled();

          const options = mockRequest.mock.calls[0][0];

          // Verify Authorization header exists and matches Bearer pattern
          expect(options.headers).toBeDefined();
          expect(options.headers.Authorization).toBeDefined();

          const authHeader = options.headers.Authorization;
          expect(authHeader).toMatch(/^Bearer .+$/);

          // Extract the token and verify it's non-empty
          const token = authHeader.replace('Bearer ', '');
          expect(token.length).toBeGreaterThan(0);
          // JWT tokens have three dot-separated parts
          expect(token.split('.').length).toBe(3);
        }
      ),
      { numRuns: 100 }
    );
  });
});
